#!/bin/bash

MAIN_BD="BD"
USER_PREFIX="user"
BD_PREFIX="BD"
USER_COUNT=10
MYSQL_ROOT_USER="Nagi"
MYSQL_ROOT_PASSWORD="zxc"

generate_password() {
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 5
}

mysql -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $MAIN_BD;"

mysql -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e "USE $MAIN_BD; CREATE TABLE IF NOT EXISTS Users (id INT(10) NOT NULL AUTO_INCREMENT, username VARCHAR(50) NOT NULL, password VARCHAR(50) NOT NULL, PRIMARY KEY (id));"

for i in $(seq 1 $USER_COUNT); do
    USERNAME="${USER_PREFIX}${i}"
    BDNAME="${BD_PREFIX}${i}"
    PASSWORD=$(generate_password)

    mysql -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $BDNAME;"

    mysql -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e "CREATE USER '$USERNAME'@'localhost' IDENTIFIED BY '$PASSWORD';"

    mysql -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON $BDNAME.* TO '$USERNAME'@'localhost';"

    mysql -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e "USE $MAIN_BD; INSERT INTO Users (username, password) VALUES ('$USERNAME', '$PASSWORD');"
done

mysql -u $MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"
